C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapWrtBad (WrtBadf2pywrap, VarNam)
      external WrtBad
      character*(*) VarNam
      logical WrtBadf2pywrap, WrtBad
      WrtBadf2pywrap = .not.(.not.WrtBad(VarNam))
      end


      subroutine f2pywrapWrtDim (WrtDimf2pywrap, DimNam, Minval)
      external WrtDim
      integer Minval
      character*(*) DimNam
      logical WrtDimf2pywrap, WrtDim
      WrtDimf2pywrap = .not.(.not.WrtDim(DimNam, Minval))
      end


      subroutine f2pywrapTstBad (TstBadf2pywrap, VarNam, RelErr)
      external TstBad
      real RelErr
      character*(*) VarNam
      logical TstBadf2pywrap, TstBad
      TstBadf2pywrap = .not.(.not.TstBad(VarNam, RelErr))
      end

